name: Housekeeping - Close stale issues   # 工作流程名称：处理陈旧问题
on:
  schedule:
    - cron: '0 9 * * *'    # 定时触发：每天早上 9 点运行

jobs:
  stale:    # 作业名称
    runs-on: ubuntu-latest    # 在最新版本的 Ubuntu 环境中运行
    steps:
      - uses: actions/stale@v9.0.0    # 使用 GitHub 官方的 stale action，版本 9.0.0
        with:
          # 当问题被标记为陈旧时的提示消息
          stale-issue-message: 'This issue is being marked stale due to a period of inactivity...'         
          # 当问题被关闭时的提示消息
          close-issue-message: 'This issue was closed because it has been stalled for 30 days...'          
          # 问题在 60 天无活动后被标记为陈旧
          days-before-issue-stale: 60
          # 问题被标记为陈旧后，再过 30 天自动关闭
          days-before-issue-close: 30        
          # 排除带有 "upcoming" 里程碑的问题
          exempt-milestones: "upcoming"                
          # 每次运行处理的最大操作数量
          operations-per-run: 1000
